Description: Simple RDS Instance template with SecretsManager
Parameters:
  RdsSettingsFunctionArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /rds/functions/engine_settings/arn
  AmazonRDSInstanceTypes:
    AllowedValues:
      - db.m1.large
      - db.m1.medium
      - db.m1.small
      - db.m1.xlarge
      - db.m2.2xlarge
      - db.m2.4xlarge
      - db.m2.xlarge
      - db.m3.2xlarge
      - db.m3.large
      - db.m3.medium
      - db.m3.xlarge
      - db.m4.10xlarge
      - db.m4.16xlarge
      - db.m4.2xlarge
      - db.m4.4xlarge
      - db.m4.large
      - db.m4.xlarge
      - db.m5.12xlarge
      - db.m5.16xlarge
      - db.m5.24xlarge
      - db.m5.2xlarge
      - db.m5.4xlarge
      - db.m5.8xlarge
      - db.m5.large
      - db.m5.xlarge
      - db.r3.2xlarge
      - db.r3.4xlarge
      - db.r3.8xlarge
      - db.r3.large
      - db.r3.xlarge
      - db.r4.16xlarge
      - db.r4.2xlarge
      - db.r4.4xlarge
      - db.r4.8xlarge
      - db.r4.large
      - db.r4.xlarge
      - db.r5.12xlarge
      - db.r5.16xlarge
      - db.r5.24xlarge
      - db.r5.2xlarge
      - db.r5.4xlarge
      - db.r5.8xlarge
      - db.r5.large
      - db.r5.xlarge
      - db.t1.micro
      - db.t2.2xlarge
      - db.t2.large
      - db.t2.medium
      - db.t2.micro
      - db.t2.small
      - db.t2.xlarge
      - db.t3.2xlarge
      - db.t3.large
      - db.t3.medium
      - db.t3.micro
      - db.t3.small
      - db.t3.xlarge
      - db.x1.16xlarge
      - db.x1.32xlarge
      - db.x1e.16xlarge
      - db.x1e.2xlarge
      - db.x1e.32xlarge
      - db.x1e.4xlarge
      - db.x1e.8xlarge
      - db.x1e.xlarge
      - db.z1d.12xlarge
      - db.z1d.2xlarge
      - db.z1d.3xlarge
      - db.z1d.6xlarge
      - db.z1d.large
      - db.z1d.xlarge
    Type: String
  RdsEngineVersion:
    AllowedValues:
      - aurora-mysql--5.7.12
      - aurora-mysql--5.7.mysql_aurora.2.03.2
      - aurora-mysql--5.7.mysql_aurora.2.03.3
      - aurora-mysql--5.7.mysql_aurora.2.03.4
      - aurora-mysql--5.7.mysql_aurora.2.04.0
      - aurora-mysql--5.7.mysql_aurora.2.04.1
      - aurora-mysql--5.7.mysql_aurora.2.04.2
      - aurora-mysql--5.7.mysql_aurora.2.04.3
      - aurora-mysql--5.7.mysql_aurora.2.04.4
      - aurora-mysql--5.7.mysql_aurora.2.04.5
      - aurora-mysql--5.7.mysql_aurora.2.04.6
      - docdb--3.6.0
      - neptune--1.0.1.0
      - aurora-postgresql--9.6.3
      - aurora-postgresql--9.6.6
      - aurora-postgresql--9.6.8
      - aurora-postgresql--9.6.9
      - aurora-postgresql--9.6.11
      - aurora-postgresql--9.6.12
      - aurora-postgresql--10.4
      - aurora-postgresql--10.5
      - aurora-postgresql--10.6
      - aurora-postgresql--10.7
      - aurora-postgresql--10.7
      - mariadb--10.0.17
      - mariadb--10.0.24
      - mariadb--10.0.28
      - mariadb--10.0.31
      - mariadb--10.0.32
      - mariadb--10.0.34
      - mariadb--10.0.35
      - mariadb--10.1.14
      - mariadb--10.1.19
      - mariadb--10.1.23
      - mariadb--10.1.26
      - mariadb--10.1.31
      - mariadb--10.1.34
      - mariadb--10.2.11
      - mariadb--10.2.12
      - mariadb--10.2.15
      - mariadb--10.2.21
      - mariadb--10.3.8
      - mariadb--10.3.13
      - mysql--5.5.46
      - mysql--5.5.53
      - mysql--5.5.54
      - mysql--5.5.57
      - mysql--5.5.59
      - mysql--5.5.61
      - mysql--5.6.34
      - mysql--5.6.35
      - mysql--5.6.37
      - mysql--5.6.39
      - mysql--5.6.40
      - mysql--5.6.41
      - mysql--5.6.43
      - mysql--5.6.44
      - mysql--5.7.16
      - mysql--5.7.17
      - mysql--5.7.19
      - mysql--5.7.21
      - mysql--5.7.22
      - mysql--5.7.23
      - mysql--5.7.24
      - mysql--5.7.25
      - mysql--5.7.26
      - mysql--8.0.11
      - mysql--8.0.13
      - mysql--8.0.15
      - mysql--8.0.16
      - oracle-ee--11.2.0.4.v1
      - oracle-ee--11.2.0.4.v3
      - oracle-ee--11.2.0.4.v4
      - oracle-ee--11.2.0.4.v5
      - oracle-ee--11.2.0.4.v6
      - oracle-ee--11.2.0.4.v7
      - oracle-ee--11.2.0.4.v8
      - oracle-ee--11.2.0.4.v9
      - oracle-ee--11.2.0.4.v10
      - oracle-ee--11.2.0.4.v11
      - oracle-ee--11.2.0.4.v12
      - oracle-ee--11.2.0.4.v13
      - oracle-ee--11.2.0.4.v14
      - oracle-ee--11.2.0.4.v15
      - oracle-ee--11.2.0.4.v16
      - oracle-ee--11.2.0.4.v17
      - oracle-ee--11.2.0.4.v18
      - oracle-ee--11.2.0.4.v19
      - oracle-ee--11.2.0.4.v20
      - oracle-ee--11.2.0.4.v21
      - oracle-ee--12.1.0.2.v1
      - oracle-ee--12.1.0.2.v2
      - oracle-ee--12.1.0.2.v3
      - oracle-ee--12.1.0.2.v4
      - oracle-ee--12.1.0.2.v5
      - oracle-ee--12.1.0.2.v6
      - oracle-ee--12.1.0.2.v7
      - oracle-ee--12.1.0.2.v8
      - oracle-ee--12.1.0.2.v9
      - oracle-ee--12.1.0.2.v10
      - oracle-ee--12.1.0.2.v11
      - oracle-ee--12.1.0.2.v12
      - oracle-ee--12.1.0.2.v13
      - oracle-ee--12.1.0.2.v14
      - oracle-ee--12.1.0.2.v15
      - oracle-ee--12.1.0.2.v16
      - oracle-ee--12.1.0.2.v17
      - oracle-ee--12.2.0.1.ru-2018-10.rur-2018-10.r1
      - oracle-ee--12.2.0.1.ru-2019-01.rur-2019-01.r1
      - oracle-ee--12.2.0.1.ru-2019-04.rur-2019-04.r1
      - oracle-ee--12.2.0.1.ru-2019-07.rur-2019-07.r1
      - oracle-ee--18.0.0.0.ru-2019-07.rur-2019-07.r1
      - oracle-se--11.2.0.4.v1
      - oracle-se--11.2.0.4.v3
      - oracle-se--11.2.0.4.v4
      - oracle-se--11.2.0.4.v5
      - oracle-se--11.2.0.4.v6
      - oracle-se--11.2.0.4.v7
      - oracle-se--11.2.0.4.v8
      - oracle-se--11.2.0.4.v9
      - oracle-se--11.2.0.4.v10
      - oracle-se--11.2.0.4.v11
      - oracle-se--11.2.0.4.v12
      - oracle-se--11.2.0.4.v13
      - oracle-se--11.2.0.4.v14
      - oracle-se--11.2.0.4.v15
      - oracle-se--11.2.0.4.v16
      - oracle-se--11.2.0.4.v17
      - oracle-se--11.2.0.4.v18
      - oracle-se--11.2.0.4.v19
      - oracle-se--11.2.0.4.v20
      - oracle-se--11.2.0.4.v21
      - oracle-se1--11.2.0.4.v1
      - oracle-se1--11.2.0.4.v3
      - oracle-se1--11.2.0.4.v4
      - oracle-se1--11.2.0.4.v5
      - oracle-se1--11.2.0.4.v6
      - oracle-se1--11.2.0.4.v7
      - oracle-se1--11.2.0.4.v8
      - oracle-se1--11.2.0.4.v9
      - oracle-se1--11.2.0.4.v10
      - oracle-se1--11.2.0.4.v11
      - oracle-se1--11.2.0.4.v12
      - oracle-se1--11.2.0.4.v13
      - oracle-se1--11.2.0.4.v14
      - oracle-se1--11.2.0.4.v15
      - oracle-se1--11.2.0.4.v16
      - oracle-se1--11.2.0.4.v17
      - oracle-se1--11.2.0.4.v18
      - oracle-se1--11.2.0.4.v19
      - oracle-se1--11.2.0.4.v20
      - oracle-se1--11.2.0.4.v21
      - oracle-se2--12.1.0.2.v2
      - oracle-se2--12.1.0.2.v3
      - oracle-se2--12.1.0.2.v4
      - oracle-se2--12.1.0.2.v5
      - oracle-se2--12.1.0.2.v6
      - oracle-se2--12.1.0.2.v7
      - oracle-se2--12.1.0.2.v8
      - oracle-se2--12.1.0.2.v9
      - oracle-se2--12.1.0.2.v10
      - oracle-se2--12.1.0.2.v11
      - oracle-se2--12.1.0.2.v12
      - oracle-se2--12.1.0.2.v13
      - oracle-se2--12.1.0.2.v14
      - oracle-se2--12.1.0.2.v15
      - oracle-se2--12.1.0.2.v16
      - oracle-se2--12.1.0.2.v17
      - oracle-se2--12.2.0.1.ru-2018-10.rur-2018-10.r1
      - oracle-se2--12.2.0.1.ru-2019-01.rur-2019-01.r1
      - oracle-se2--12.2.0.1.ru-2019-04.rur-2019-04.r1
      - oracle-se2--12.2.0.1.ru-2019-07.rur-2019-07.r1
      - oracle-se2--18.0.0.0.ru-2019-07.rur-2019-07.r1
      - aurora--5.6.10a
      - aurora--5.6.10a
      - aurora--5.6.10a
      - aurora--5.6.10a
      - aurora--5.6.10a
      - aurora--5.6.mysql_aurora.1.19.0
      - aurora--5.6.mysql_aurora.1.19.0
      - aurora--5.6.mysql_aurora.1.19.1
      - aurora--5.6.mysql_aurora.1.19.2
      - aurora--5.6.mysql_aurora.1.19.2
      - aurora--5.6.mysql_aurora.1.19.5
      - postgres--9.3.12
      - postgres--9.3.14
      - postgres--9.3.16
      - postgres--9.3.17
      - postgres--9.3.19
      - postgres--9.3.20
      - postgres--9.3.22
      - postgres--9.3.23
      - postgres--9.3.24
      - postgres--9.3.25
      - postgres--9.4.7
      - postgres--9.4.9
      - postgres--9.4.11
      - postgres--9.4.12
      - postgres--9.4.14
      - postgres--9.4.15
      - postgres--9.4.17
      - postgres--9.4.18
      - postgres--9.4.19
      - postgres--9.4.20
      - postgres--9.4.21
      - postgres--9.4.23
      - postgres--9.5.2
      - postgres--9.5.4
      - postgres--9.5.6
      - postgres--9.5.7
      - postgres--9.5.9
      - postgres--9.5.10
      - postgres--9.5.12
      - postgres--9.5.13
      - postgres--9.5.14
      - postgres--9.5.15
      - postgres--9.5.16
      - postgres--9.5.18
      - postgres--9.6.1
      - postgres--9.6.2
      - postgres--9.6.3
      - postgres--9.6.5
      - postgres--9.6.6
      - postgres--9.6.8
      - postgres--9.6.9
      - postgres--9.6.10
      - postgres--9.6.11
      - postgres--9.6.12
      - postgres--9.6.14
      - postgres--10.1
      - postgres--10.3
      - postgres--10.4
      - postgres--10.5
      - postgres--10.6
      - postgres--10.7
      - postgres--10.9
      - postgres--11.1
      - postgres--11.2
      - postgres--11.4
      - sqlserver-ee--11.00.5058.0.v1
      - sqlserver-ee--11.00.6020.0.v1
      - sqlserver-ee--11.00.6594.0.v1
      - sqlserver-ee--11.00.7462.6.v1
      - sqlserver-ee--12.00.5000.0.v1
      - sqlserver-ee--12.00.5546.0.v1
      - sqlserver-ee--12.00.5571.0.v1
      - sqlserver-ee--13.00.2164.0.v1
      - sqlserver-ee--13.00.4422.0.v1
      - sqlserver-ee--13.00.4451.0.v1
      - sqlserver-ee--13.00.4466.4.v1
      - sqlserver-ee--13.00.4522.0.v1
      - sqlserver-ee--13.00.5216.0.v1
      - sqlserver-ee--13.00.5292.0.v1
      - sqlserver-ee--14.00.1000.169.v1
      - sqlserver-ee--14.00.3015.40.v1
      - sqlserver-ee--14.00.3035.2.v1
      - sqlserver-ee--14.00.3049.1.v1
      - sqlserver-ex--11.00.5058.0.v1
      - sqlserver-ex--11.00.6020.0.v1
      - sqlserver-ex--11.00.6594.0.v1
      - sqlserver-ex--11.00.7462.6.v1
      - sqlserver-ex--12.00.4422.0.v1
      - sqlserver-ex--12.00.5000.0.v1
      - sqlserver-ex--12.00.5546.0.v1
      - sqlserver-ex--12.00.5571.0.v1
      - sqlserver-ex--13.00.2164.0.v1
      - sqlserver-ex--13.00.4422.0.v1
      - sqlserver-ex--13.00.4451.0.v1
      - sqlserver-ex--13.00.4466.4.v1
      - sqlserver-ex--13.00.4522.0.v1
      - sqlserver-ex--13.00.5216.0.v1
      - sqlserver-ex--13.00.5292.0.v1
      - sqlserver-ex--14.00.1000.169.v1
      - sqlserver-ex--14.00.3015.40.v1
      - sqlserver-ex--14.00.3035.2.v1
      - sqlserver-ex--14.00.3049.1.v1
      - sqlserver-se--11.00.5058.0.v1
      - sqlserver-se--11.00.6020.0.v1
      - sqlserver-se--11.00.6594.0.v1
      - sqlserver-se--11.00.7462.6.v1
      - sqlserver-se--12.00.4422.0.v1
      - sqlserver-se--12.00.5000.0.v1
      - sqlserver-se--12.00.5546.0.v1
      - sqlserver-se--12.00.5571.0.v1
      - sqlserver-se--13.00.2164.0.v1
      - sqlserver-se--13.00.4422.0.v1
      - sqlserver-se--13.00.4451.0.v1
      - sqlserver-se--13.00.4466.4.v1
      - sqlserver-se--13.00.4522.0.v1
      - sqlserver-se--13.00.5216.0.v1
      - sqlserver-se--13.00.5292.0.v1
      - sqlserver-se--14.00.1000.169.v1
      - sqlserver-se--14.00.3015.40.v1
      - sqlserver-se--14.00.3035.2.v1
      - sqlserver-se--14.00.3049.1.v1
      - sqlserver-web--11.00.5058.0.v1
      - sqlserver-web--11.00.6020.0.v1
      - sqlserver-web--11.00.6594.0.v1
      - sqlserver-web--11.00.7462.6.v1
      - sqlserver-web--12.00.4422.0.v1
      - sqlserver-web--12.00.5000.0.v1
      - sqlserver-web--12.00.5546.0.v1
      - sqlserver-web--12.00.5571.0.v1
      - sqlserver-web--13.00.2164.0.v1
      - sqlserver-web--13.00.4422.0.v1
      - sqlserver-web--13.00.4451.0.v1
      - sqlserver-web--13.00.4466.4.v1
      - sqlserver-web--13.00.4522.0.v1
      - sqlserver-web--13.00.5216.0.v1
      - sqlserver-web--13.00.5292.0.v1
      - sqlserver-web--14.00.1000.169.v1
      - sqlserver-web--14.00.3015.40.v1
      - sqlserver-web--14.00.3035.2.v1
      - sqlserver-web--14.00.3049.1.v1
    Type: String
  RdsInstancePrefix:
    Type: String
  RdsSnapthotId:
    Default: none
    Description: ID of the Snapshot to create the DB Instance from
    Type: String
  RootStackName:
    Type: String
  StorageSubnets:
    Type: List<AWS::EC2::Subnet::Id>
  VpcDnsZone:
    AllowedPattern: '[a-z0-9-.]+'
    Default: cluster.local
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  VpcZoneId:
    Type: String

Conditions:
  NotUseSnapshot: !Equals
    - !Ref 'RdsSnapthotId'
    - none
  UseSnapshot: !Not
    - !Condition 'NotUseSnapshot'
  GeneratePassword: !Not
    - !Condition 'GeneratePassword'
  NotGeneratePassword: !Not
    - !Condition 'GeneratePassword'
  UseAuroraCluster: !Equals
    - aurora
    - !Select
      - 0
      - !Split
        - '-'
        - !Ref 'RdsEngineVersion'
  UseClassicRds: !Not
    - !Condition 'UseAuroraCluster'


Resources:
  lambdaGetDBEngineVersion:
    Type: AWS::CloudFormation::CustomResource
    Version: '1.0'
    Properties:
      ServiceToken: ${RdsSettingsFunctionArn}
      EngineName: !Select
        - 0
        - Fn::Split:
            - '--'
            - !Ref RdsEngineVersion
      EngineVersion: !Select
        - 1
        - Fn::Split:
            - '--'
            - !Ref RdsEngineVersion

  RdsClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Condition: UseAuroraCluster
    Properties:
      Description: 'Default settings for Aurora engine'
      Family: !GetAtt 'lambdaGetDBEngineVersion.DBParameterGroupFamily'

  RdsAuroraDbCluster:
    Condition: UseAuroraCluster
    Properties:
      DBClusterParameterGroupName: !Ref RdsClusterParameterGroup
      DBSubnetGroupName: !Ref 'RdsDbSubnetGroup'
      Engine: !Select
        - 0
        - !Split
          - --
          - !Ref 'RdsEngineVersion'
      EngineVersion: !Select
        - 1
        - !Split
          - --
          - !Ref 'RdsEngineVersion'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${RdsDbSecret}:SecretString:password}}'
      MasterUsername: !If
        - NotUseSnapshot
        - !Sub '{{resolve:secretsmanager:${RdsDbSecret}:SecretString:username}}'
        - !Ref 'AWS::NoValue'
      StorageEncrypted: 'true'
      VpcSecurityGroupIds:
        - !Ref 'RdsSecurityGroup'
    Type: AWS::RDS::DBCluster
  RdsDbInstance:
    Properties:
      AllocatedStorage: !If
        - UseClassicRds
        - 256
        - !Ref 'AWS::NoValue'
      DBClusterIdentifier: !If
        - UseAuroraCluster
        - !Ref 'RdsAuroraDbCluster'
        - !Ref 'AWS::NoValue'
      DBInstanceClass: !Ref 'AmazonRDSInstanceTypes'
      DBSnapshotIdentifier: !If
        - UseSnapshot
        - !Ref 'RdsSnapthotId'
        - !Ref 'AWS::NoValue'
      DBSubnetGroupName: !Ref 'RdsDbSubnetGroup'
      Engine: !Select
        - 0
        - !Split
          - --
          - !Ref 'RdsEngineVersion'
      EngineVersion: !Select
        - 1
        - !Split
          - --
          - !Ref 'RdsEngineVersion'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${RdsDbSecret}:SecretString:password}}'
      MasterUsername: !If
        - NotUseSnapshot
        - !Sub '{{resolve:secretsmanager:${RdsDbSecret}:SecretString:username}}'
        - !Ref 'AWS::NoValue'
      StorageEncrypted: 'true'
      StorageType: !If
        - UseClassicRds
        - gp2
        - !Ref 'AWS::NoValue'
      VPCSecurityGroups:
        - !Ref 'RdsSecurityGroup'
    Type: AWS::RDS::DBInstance
  RdsDbSecret:
    Properties:
      GenerateSecretString: !If
        - GeneratePassword
        - ExcludeCharacters: <>%`|;,.
          ExcludeLowercase: 'false'
          ExcludePunctuation: 'true'
          ExcludeUppercase: 'false'
          GenerateStringKey: password
          IncludeSpace: 'false'
          PasswordLength: 32
          RequireEachIncludedType: 'true'
          SecretStringTemplate: '{"username":"postgres"}'
        - !Ref 'AWS::NoValue'
      SecretString: !If
        - NotGeneratePassword
        - '{"username":"postgres", "password":"payments"}'
        - !Ref 'AWS::NoValue'
    Type: AWS::SecretsManager::Secret
  RdsDbSubnetGroup:
    Properties:
      DBSubnetGroupDescription: !Sub 'Subnets for RDS in ${AWS::StackName}'
      SubnetIds: !Ref 'StorageSubnets'
    Type: AWS::RDS::DBSubnetGroup
  RdsInstanceDnsAlias:
    DependsOn:
      - RdsDbInstance
    Properties:
      HostedZoneId: !Ref 'VpcZoneId'
      Name: !Sub '${RdsInstancePrefix}.${RootStackName}.${VpcDnsZone}'
      ResourceRecords:
        - !GetAtt 'RdsDbInstance.Endpoint.Address'
      TTL: 60
      Type: CNAME
    Type: AWS::Route53::RecordSet
  RdsSecurityGroup:
    Properties:
      GroupDescription: !Sub 'SG for RDS - ${AWS::StackName}'
      Tags:
        - Key: Name
          Value: !Sub 'sg-rds-${AWS::StackName}'
      VpcId: !Ref 'VpcId'
    Type: AWS::EC2::SecurityGroup
  SecretRdsClusterAttachment:
    Condition: UseAuroraCluster
    DependsOn:
      - RdsAuroraDbCluster
      - RdsDbSecret
    Properties:
      SecretId: !Ref 'RdsDbSecret'
      TargetId: !Ref 'RdsAuroraDbCluster'
      TargetType: AWS::RDS::DBCluster
    Type: AWS::SecretsManager::SecretTargetAttachment
  SecretRdsInstanceAttachment:
    Condition: UseClassicRds
    DependsOn:
      - RdsDbInstance
      - RdsDbSecret
    Properties:
      SecretId: !Ref 'RdsDbSecret'
      TargetId: !Ref 'RdsDbInstance'
      TargetType: AWS::RDS::DBInstance
    Type: AWS::SecretsManager::SecretTargetAttachment

Outputs:
  RdsInstanceEndpoint:
    Export:
      Name: !Sub '${AWS::StackName}-RdsInstanceEndpoint'
    Value: !GetAtt 'RdsDbInstance.Endpoint.Address'
  RdsInstancePort:
    Export:
      Name: !Sub '${AWS::StackName}-RdsInstancePort'
    Value: !GetAtt 'RdsDbInstance.Endpoint.Port'
  RdsInstancePrefix:
    Export:
      Name: !Sub '${AWS::StackName}-RdsInstancePrefix'
    Value: !Ref 'RdsInstanceDnsAlias'
  RdsIntanceSecurityGroup:
    Export:
      Name: !Sub '${AWS::StackName}-RdsIntanceSecurityGroup'
    Value: !Ref 'RdsSecurityGroup'
  RdsRootPasswordArn:
    Export:
      Name: !Sub '${AWS::StackName}-RdsRootPasswordArn'
    Value: !Ref 'RdsDbSecret'
  StackName:
    Export:
      Name: !Sub '${AWS::StackName}-StackName'
    Value: !Ref 'AWS::StackName'
